"""Public document intake API."""

from .basic_chunking import (
    Chunk,
    ChunkingStats,
    TokenChunk,
    TokenChunkingStats,
    calculate_chunk_stats,
    calculate_token_chunk_stats,
    token_chunks,
)
from .chunking import DocumentChunk, chunk_document, chunk_page
from .cleaning import CleanedPage, clean_page, clean_text
from .embeddings import (
    EmbeddedChunk,
    EmbeddingError,
    EmbeddingManifest,
    EmbeddingResult,
    EmbeddingRunSummary,
    call_embedding_api_with_retry,
    cosine_similarity,
    estimate_cost,
    generate_chunk_id,
    generate_embeddings,
    get_embedding_config,
    load_existing_embeddings,
    prepare_chunks_from_basic_chunks,
    prepare_chunks_from_token_chunks,
    rank_chunks_by_similarity,
    save_embeddings_incremental,
    validate_embeddings,
)
from .loader import (
    CorpusIngestionResult,
    DocumentLoadError,
    DocumentPage,
    ingest_corpus,
    load_document,
)
from .metadata import tag_chunks
from .pipeline import IngestionResult, ingest

__all__ = [
    "Chunk",
    "ChunkingStats",
    "TokenChunk",
    "TokenChunkingStats",
    "calculate_chunk_stats",
    "calculate_token_chunk_stats",
    "token_chunks",
    "DocumentChunk",
    "chunk_document",
    "chunk_page",
    "DocumentLoadError",
    "DocumentPage",
    "load_document",
    "CleanedPage",
    "clean_page",
    "clean_text",
    "CorpusIngestionResult",
    "ingest_corpus",
    "tag_chunks",
    "IngestionResult",
    "ingest",
    "EmbeddingError",
    "EmbeddingManifest",
    "EmbeddingResult",
    "EmbeddingRunSummary",
    "EmbeddedChunk",
    "call_embedding_api_with_retry",
    "cosine_similarity",
    "estimate_cost",
    "generate_chunk_id",
    "generate_embeddings",
    "get_embedding_config",
    "load_existing_embeddings",
    "prepare_chunks_from_basic_chunks",
    "prepare_chunks_from_token_chunks",
    "rank_chunks_by_similarity",
    "save_embeddings_incremental",
    "validate_embeddings",
]
